name: Build on various RaspberryPi OS versions
on:
  push:
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target: [raspbian, raspios, raspios64]
        include:
        - target: raspbian
          cpu: arm1176
          base_image: raspbian_lite:latest
        - target: raspios
          cpu: arm1176
          base_image: raspios_lite:latest
        - target: raspios64
          cpu: cortex-a53
          base_image: raspios_lite_arm64:latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        image_additional_mb: 1024
        commands: |
            apt-get update -y --allow-releaseinfo-change
            apt-get install --no-install-recommends -y erlang-nox erlang-dev
            erts_version=`erl +V 2>&1 | sed -E -e 's|.+ emulator version ||g'`
            case "${erts_version}" in
                "10.0"*|"10.1"*|"10.2"*|"10.3"*)
                    # OTP 21
                    wget https://github.com/erlang/rebar3/releases/download/3.15.1/rebar3
                    ;;
                "10."*)
                    # OTP 22
                    wget https://github.com/erlang/rebar3/releases/download/3.18.0/rebar3
                    ;;
                "11."*)
                    # OTP 23
                    wget https://github.com/erlang/rebar3/releases/download/3.20.0/rebar3
                    ;;
                "12."*)
                    # OTP 24
                    # 3.23.0 is latest release and works with OTP24.
                    # However, OTP27 has been released and future releases might not work
                    wget https://github.com/erlang/rebar3/releases/download/3.23.0/rebar3
                    ;;
                *)
                    wget https://s3.amazonaws.com/rebar3/rebar3
                    ;;
            esac
            chmod +x rebar3
            ./rebar3 release
